const animalData = [
  {
    name: 'Enrico',
    species: 'Hund',
    sex: 'männlich',
    race: 'Laika',
    birthday: '2009-11-02',
    tags: ['kastriert', 'kinderfreundlich', 'viel Auslauf'],
  },
  {
    name: 'Tico',
    species: 'Hund',
    sex: 'männlich',
    race: 'Dackel-Mix',
    birthday: '2019-09-28',
    tags: ['Für Anfänger', 'viel Auslauf'],
  },
  {
    name: 'Hilde',
    species: 'Hund',
    sex: 'weiblich',
    race: 'Schnauzer-Mix',
    birthday: '2011-03-15',
    tags: ['Stadthund', 'Mag Hunde'],
  },
  {
    name: 'Susi',
    species: 'Katze',
    sex: 'weiblich',
    race: 'EKH',
    birthday: '2014-04-10',
    tags: ['Wohnungskatze', 'Einzelgänger'],
  },
  {
    name: 'Kalle',
    species: 'Katze',
    sex: 'männlich',
    race: 'EKH',
    birthday: '2020-06-01',
    tags: ['Freigänger', 'Mag Katzen'],
  },
  {
    name: 'Rosi',
    species: 'Katze',
    sex: 'weiblich',
    race: 'EKH',
    birthday: '2016-08-22',
    tags: ['Freigänger', 'kinderfreundlich'],
  },
];
